### PR TITLE
ability to return active roster based on team id

### PR DESCRIPTION
**Pull request by tyrohellion**
lets the user input a team id and returns the team's roster

### CODE REVIEW

**Comment by amas0** [comment]
Looks good to me, thanks for the PR!

**Comment by amas0** [comment]
Actually, just realized -- can you not get the same behavior with:

```python
from octanegg import Octane

octane = Octane()

octane.get_players(team="team_id")
```

Quick test I did was:

```python
octane.get_players(team="team_id") == octane.get_players_by_team_id('team_id')
```

Which returned `True`.

**Comment by tyrohellion** [comment]
I haven't really tried every way, I was having trouble because I originally tried to get rosters by /players/teamid. For example if we use Spacestation Gaming the url: /players/6020bc70f1e4807cc7002389 returns: active_roster: [] with nothing in the brackets. Instead of trying other ways this for me was the easiest way. You're probably right though

**Comment by amas0** [comment]
It looks like the generated get url via `octane.get_players(team="6020bc70f1e4807cc7002389")` is `https://zsr.octane.gg/players?perPage=100&team=6020bc70f1e4807cc7002389&page=1`.

The `page` bits are irrelevant because only a few results are returned, but I do get results back for SSG. I think it was probably just a tricky thing because filtering the `/players` endpoint mostly happens with query params.

**Comment by tyrohellion** [comment]
Oh ok I see, thanks for the clarification

**Pull request closed without merging**
